In [70]:
import numpy as np

In [2]:
lst = [1,2,3]

np.array(lst)

array([1, 2, 3])

In [6]:
lst_1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(lst_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [19]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [20]:
np.eye(4) #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(4) #random numbers from a uniform distribution over 0 to 1

array([0.5126512 , 0.36807942, 0.80716472, 0.61377557])

In [24]:
np.random.rand(5,5)

array([[0.95763234, 0.52032412, 0.56202421, 0.20787755, 0.66941008],
       [0.54067905, 0.29447586, 0.0963543 , 0.17511287, 0.84989704],
       [0.72446999, 0.31898111, 0.91727375, 0.31271882, 0.07799074],
       [0.54270663, 0.48297662, 0.84578558, 0.09410775, 0.13604986],
       [0.59587698, 0.93318903, 0.18357736, 0.22230936, 0.22024104]])

In [25]:
np.random.rand(3,4)

array([[0.71444303, 0.84130177, 0.96189529, 0.59051911],
       [0.30341637, 0.24032209, 0.21151211, 0.79096392],
       [0.82538637, 0.03813944, 0.22632368, 0.05593566]])

In [26]:
np.random.randn(3) #Normal distribution centered around 0

array([ 0.1878342 , -0.31509478, -1.55007294])

In [27]:
np.random.randn(5,3)

array([[ 1.44697948,  1.30649876, -1.16278333],
       [-0.99820182,  0.20658421, -1.29299615],
       [ 1.43689763, -0.33907708, -0.94099289],
       [ 0.21237312,  0.37021806,  0.82214523],
       [ 2.2562495 ,  1.50761876,  1.16257732]])

In [28]:
np.random.randint(2,10,5) #random integers

array([6, 2, 8, 6, 2])

In [29]:
np.random.randint(4,530,8)

array([ 81,  77, 526, 275,  75, 312,  84, 180])

In [3]:
my_arr = np.random.randint(0,51,24)
my_arr

array([25, 29, 25,  7, 32,  3, 42, 10,  7, 42,  5,  3,  6, 12, 32,  1, 15,
       23, 41, 13, 15, 14, 34, 45], dtype=int32)

In [4]:
my_arr.reshape(4,6)

array([[25, 29, 25,  7, 32,  3],
       [42, 10,  7, 42,  5,  3],
       [ 6, 12, 32,  1, 15, 23],
       [41, 13, 15, 14, 34, 45]], dtype=int32)

In [5]:
my_arr.reshape(8,3)

array([[25, 29, 25],
       [ 7, 32,  3],
       [42, 10,  7],
       [42,  5,  3],
       [ 6, 12, 32],
       [ 1, 15, 23],
       [41, 13, 15],
       [14, 34, 45]], dtype=int32)

In [6]:
my_arr.max()

np.int32(45)

In [7]:
my_arr.min()

np.int32(1)

In [8]:
my_arr.argmax()

np.int64(23)

In [9]:
my_arr.argmin()

np.int64(15)

In [12]:
my_arr.dtype

dtype('int32')

24/09/2024

Numpy Indexing and Selection

In [23]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[5]

np.int64(5)

In [18]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [30]:
# arr[2:6] = 10

arr[:3] = (110,9,8)

In [31]:
arr

array([110,   9,   8,   3,   4,   5,   6,   7,   8,   9,  10])

In [40]:
arr_rep = np.arange(0,11)

arr_rep

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_arr_rep = arr_rep[:5]
slice_arr_rep

array([0, 1, 2, 3, 4])

In [44]:
slice_arr_rep[:] = 99


In [45]:
slice_arr_rep

array([99, 99, 99, 99, 99])

In [46]:
arr_rep 
# numpy doesn't make copies of array
# Slicing is essentially a sliced view of array not a sliced copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_rep_cp = arr_rep.copy()

In [50]:
arr_rep_cp[:5] = (12,23,34,45,56)

In [52]:
print(arr_rep)
print(arr_rep_cp)

[99 99 99 99 99  5  6  7  8  9 10]
[12 23 34 45 56  5  6  7  8  9 10]


2D Arrays....

In [57]:
arr_2d = np.arange(5,50,5).reshape(3,3)

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0]

array([ 5, 10, 15])

In [65]:
arr_2d[1][2]

np.int64(30)

In [66]:
arr_2d[1,2]

np.int64(30)

In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [74]:
arr_2d[1,1:]

array([25, 30])

In [75]:
arra = np.arange(1,11)

arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
bool_arra = arra > 5

In [78]:
bool_arra

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [80]:
arra[bool_arra]

array([ 6,  7,  8,  9, 10])

In [81]:
arra[arra>5]

array([ 6,  7,  8,  9, 10])

Numpy Operations......

    Array with Array

In [84]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
# arr1 + arr1

# arr1 - 2

# arr1 * arr1

arr1 // 3

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3])

In [87]:
arr1 + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [94]:
arr1 ** arr1

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])